<div id="contentBox">
    <h1>Admin Area</h1>

    <div id="controlPanelIconsBox">
        <div class="adminControl" id="addStockControl">
            <a href="">
                <div class="adminControlIcon" id="addStockIcon"></div>
                <div class="adminControlCaption">New Stock</div>
            </a>
        </div>

        <div class="adminControl" id="editUserControl">
            <a href="">
                <div class="adminControlIcon" id="editUserIcon"></div>
                <div class="adminControlCaption">Manage Members</div>
            </a>
        </div>

        <div class="adminControl" id="manageInvoicesControl">
            <a href="">
                <div class="adminControlIcon" id="manageInvoicesIcon"></div>
                <div class="adminControlCaption">Manage Invoices</div>
            </a>

            <a href="admin.php?logout"><div class="formCSSButton">Sign Out</div></a>
        </div>
    </div>
</div>