<div id="contentBox">

    <h1>Admin Area</h1>

    <div id="signInBoxAdmin">
        <fieldset class="signInFieldSet">
            <legend>Sign in</legend>
            <div><label>Email:</label><span class="inputSpan"><input type="text" class="inputTextBox" /></span></div>
            <div><label>Password:</label><span class="inputSpan"><input type="password" class="inputTextBox" /></span></div>
            <div><label>Remmeber:</label><input type="checkbox" name="remember" checked/></div>
            <a href="adminControlPanel.html"><div class="formCSSButton">Sign in</div></a>
        </fieldset>
    </div>
</div>