<?php

/* 
 * This include display the categories (brands) box
 */
?>

<div id="categoryBox">
    <a href="search.php?brand=fender"><div class="categoryImage" id="fenderCategory"></div></a>
    <a href="search.php?brand=gibson"><div class="categoryImage" id="gibsonCategory"></div></a>
    <a href="search.php?brand=b.c. rich"><div class="categoryImage" id="bcRichCategory"></div></a>
    <a href="search.php?brand=jackson"><div class="categoryImage" id="jacksonLogo"></div></a> 
</div>